### ISSUE TITLE
If --config of module's hook failed, hook ignored

### ISSUE THREAD

**Issue by driusha** [flant/addon-operator#31] opened 2019-07-18 11:58 UTC
If hook returns invalid json for --config request, addon-operator just ignores this hook.
In this case addon-operator must fail or keep trying to --config.

**Comment by diafour** [comment] 2019-07-18 19:22
When error occured during configuration of module hooks, then configuration is keeping retried.
The error can be exit non zero or problems unmarshaling json. There is no validation of bindings for now.

**Comment by diafour** [comment] 2019-07-23 09:55
Bug is reproduced: operator runs `hook --config` for all hooks of module and adds successful hooks into index. When `hook --config` is failed, then index is not cleaned. The next discover task doesn't initialize module hooks because index for module has entries with successful hooks.

**Comment by distol** [comment] 2019-08-15 16:43
Fixed in #33

**Closed by distol** 2019-08-15 16:43 UTC
